name: WinGet Submission

permissions:
  contents: read

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  winget:
    if: github.event.release.prerelease == false
    name: Submit to WinGet
    runs-on: ubuntu-latest
    steps:
      - name: Submit to WinGet
        uses: vedantmgoyal9/winget-releaser@v2
        with:
          identifier: justnullname.QuickView
          token: ${{ secrets.WINGET_TOKEN }}
          installers-regex: '.*_Installer_.*\.exe$'
